service: github-status-checks

# Use serverless-webpack plugin to transpile ES6/ES7
plugins:
  - serverless-webpack

# Enable auto-packing of external modules
custom:
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1
  profile: robc@theodo.co.uk
  iamRoleStatements:
    - Effect: Allow
      Action: ssm:GetParameters
      Resource: '*'

functions:
  githubWebhookListener:
    handler: handler.githubWebhookListener
    description: Listens for pull request events and checks titles
    events:
      - http:
          path: webhook
          method: post
          cors: true
